### ISSUE TITLE
Make Schemas folder a submodule

### ISSUE THREAD

**Issue by nalgeon** [Belianin/iuliia-cs#3]
You might want to make `Iuliia/Schemas` folder a git submodule pointing to `https://github.com/nalgeon/iuliia` repo. This will make it easier to keep schemas up to date.

If you consider doing so:

1. Delete existing Schemas folder and commit.
2. Re-add it as submodule:
```sh
git submodule add https://github.com/nalgeon/iuliia Iuliia/Schemas
```
3. Commit and push.

**Comment by Belianin** [comment]
Thanks for your advice!
I did what you told me, so now life of this repository is in your hands. Unfortunately, i can't make schemes to be loaded dynamically in C#, so if one of them is deleted it will cause a compile time error.

Anyway, it will has no effect existing nuget-packages and i don't believe that this will ever happen

**Comment by nalgeon** [comment]
The state of `Schemas` folder is bound to specific revision on `iuliia` repo, and it won't update on its own — only if you `git pull` it. So it won't break in such way that will remain unnoticed.
