### ISSUE TITLE
Update NuGet package. Fixed cyrillic е instead of latin e in map

### ISSUE THREAD

**Issue by askalione** [Belianin/iuliia-cs#7]
Hello!

Can you please update NuGet package, because `gost_779_alt.json` was fixed in submodule -
https://github.com/nalgeon/iuliia/commit/3a83da8a8d3a02c03639a55de2647f16ff3250e0 ?

**Comment by askalione** [comment]
Up

**Comment by Belianin** [comment]
Hello!
I'm so sorry i didn't notice your issue earlier. I know that you forked this reposiroty already, but i released version 2.0.4 anyway
